# alpha-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-deployment-user-%USER%
spec:
  selector:
    matchLabels:
      app: alpha-user-%USER%
  replicas: 1
  template:
    metadata:
      labels:
        app: alpha-user-%USER%
    spec:
      containers:
        - name: alpha
          image: %IMAGE%
          imagePullPolicy: Always
          ports:
            - containerPort: 5900
              name: "vnc"
            - containerPort: 6900
              name: "novnc"
          env:
          - name: USER_NAME
            value: %USER%
          - name: SECRET_TOKEN
            value: %SECRET_TOKEN%
          - name: USERID
            value: %USERID%
