# alpha-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-portal
spec:
  selector:
    matchLabels:
      app: web-portal
  replicas: 2
  template:
    metadata:
      labels:
        app: web-portal
    spec:
      containers:
        - name: web-portal
          image: localhost:32000/web-portal
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: "http"


